version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
