version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules

